name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create release
      run: |
        zip -r release.zip .
        gh release create --latest 'release.zip' 
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
