name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create release
      run: |
        if gh release view latest; then
          gh release delete latest --yes
        fi
        zip -r latest.zip .
        gh release create latest 'latest.zip' --title latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
