name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Zip the code
      run: zip -r latest.zip .

    - name: Create a release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'latest'
        release_name: 'Latest'
        draft: false
        prerelease: false
        files: latest.zip
